/* =========================================================
   LA OTRA COLOMBIA — datos del portafolio principal
   Para agregar una foto nueva: copia un bloque {...} y cambia
   img, title, story y category. No toques el HTML.
   ========================================================= */
const PORTFOLIO_DATA = [
  { img:"images/port-mula-cana.jpg", title:"El peso del camino", story:"En Chaguaní, la caña se carga a lomo de mula, como siempre se ha hecho.", category:"La Fuerza de lo Cotidiano" },
  { img:"images/port-herencia-wayuu.jpg", title:"Herencia wayuu", story:"El color y la tradición se heredan antes que las palabras, en La Guajira.", category:"Herencia Viva" },
  { img:"images/port-cano-cristales-panoramica.jpg", title:"El río de cinco colores", story:"Caño Cristales se tiñe de rojo cada año, un fenómeno único en el mundo.", category:"Entre Agua y Montaña" },
  { img:"images/port-hilando-huso.jpg", title:"El hilo que no se rompe", story:"Con un huso de madera, una tradición de siglos sigue girando entre sus manos.", category:"Herencia Viva" },
  { img:"images/port-esquileo.jpg", title:"El esquileo", story:"Cada temporada, la lana se convierte en abrigo para el frío que viene.", category:"Rituales de la Tierra" },
  { img:"images/port-rueca-boyaca.jpeg", title:"El camino del agua", story:"En la Guajira, el acceso al agua exige recorrer largas distancias.", category:"Guardianes del Tiempo" },
  { img:"images/port-taller-ceramica.jpg", title:"Manos de barro", story:"En un taller de Ráquira, la arcilla se convierte en color bajo manos expertas.", category:"Oficios que Permanecen" },
  { img:"images/port-lena-diaria.jpg", title:"La leña de cada día", story:"Cada tarde repite el mismo gesto: partir la leña que alimentará el fogón.", category:"Oficios que Permanecen" },
  { img:"images/port-bordar-memoria.jpg", title:"Bordar la memoria", story:"Cada puntada borda no solo tela, sino la historia de quien la teje.", category:"Oficios que Permanecen" },
  { img:"images/port-rebano-mongui.jpg", title:"Rebaño en la plaza", story:"Frente al convento de Monguí, el arreo diario cruza la piedra colonial.", category:"Voces del Camino" },
  { img:"images/port-pulso-corral.jpg", title:"El pulso del corral", story:"Entre el barro y el ganado, la faena no distingue cansancio.", category:"La Fuerza de lo Cotidiano" },
  { img:"images/port-guardian-corral.jpg", title:"Guardián del corral", story:"El ganado define el paisaje y la economía de estas sabanas.", category:"Geografías Vivas" },
  { img:"images/port-polvo-llanero.jpg", title:"Faena de doma", story:"El polvo que levantan los caballos es la respiración misma de los Llanos.", category:"Geografías Vivas" },
  { img:"images/port-cruzar-territorio.jpg", title:"Cruzar el territorio", story:"En el Chocó, niños a orillas del rio Atrato que conecta comunidades que el mapa casi no nombra.", category:"Huellas del Territorio" },
  { img:"images/port-rio-camino.jpg", title:"El río como camino", story:"Cuatro hombres, una canoa y un río que ha sido carretera desde siempre.", category:"Voces del Camino" },
  { img:"images/port-nudo-a-nudo.jpg", title:"Nudo a nudo", story:"En Cota, la artesana Elvia Tauta teje sus canastos con la misma paciencia de siempre.", category:"Oficios que Permanecen" },
  { img:"images/port-hoja-tabaco.jpg", title:"Mirada llanera", story:"En el Hato El Boral, Casanare, un llanero hace una pausa en medio de la faena diaria.", category:"Voces del Camino" },
  { img:"images/port-la-otra-orilla.jpg", title:"Fuerza de mujer", story:"En el trabajo del Llano, la fuerza de las mujeres no le pide permiso a nadie.", category:"La Fuerza de lo Cotidiano" },

  { img:"images/port-mompox-01.jpg", title:"Mompox y su río", story:"El tiempo parece detenerse en las calles coloniales frente al Magdalena.", category:"Donde Habita la Memoria" },
  { img:"images/port-mompox-02.jpg", title:"Reflejos de Mompox", story:"La arquitectura republicana se duplica en las aguas quietas del río.", category:"Donde Habita la Memoria" },
  { img:"images/port-barichara-01.jpg", title:"Piedra y luz de Barichara", story:"Cada calle empedrada guarda tres siglos de historia colonial intactos.", category:"Donde Habita la Memoria" },
  { img:"images/port-barichara-02.jpg", title:"Callejón guane", story:"Entre muros de tapia pisada, Barichara conserva su trazado original.", category:"Donde Habita la Memoria" },
  { img:"images/port-cartagena.jpg", title:"Cartagena de Indias", story:"Entre murallas y balcones, el Caribe colombiano guarda su historia amurallada.", category:"Donde Habita la Memoria" },
  { img:"images/port-villa-de-leyva.jpg", title:"La plaza más grande", story:"Villa de Leyva conserva una de las plazas coloniales más extensas de América.", category:"Donde Habita la Memoria" },
  { img:"images/port-jerico-01.jpg", title:"Jericó, cuna de colores", story:"Las fachadas de Jericó guardan la memoria cafetera de Antioquia.", category:"Donde Habita la Memoria" },
  { img:"images/port-jerico-02.jpg", title:"Balcones de Jericó", story:"La arquitectura republicana se asoma entre montañas del suroeste antioqueño.", category:"Donde Habita la Memoria" },
  { img:"images/port-puerto-honda.jpg", title:"El puerto sobre el Magdalena", story:"Honda fue por siglos la puerta fluvial hacia el interior del país.", category:"Herencia Viva" },
  { img:"images/port-catedral-sal.jpg", title:"La Catedral de Sal", story:"A 180 metros bajo tierra, la fe se talló directamente en la roca de sal.", category:"Donde Habita la Memoria" },
  { img:"images/port-casas-sobre-agua.jpg", title:"Casas sobre el agua", story:"En la ciénaga, comunidades enteras han vivido sobre el agua por generaciones.", category:"Herencia Viva" },

  { img:"images/port-territorio-abierto.jpg", title:"El arte de la pesca", story:"En Honda, los pescadores tejen y remiendan sus redes antes de salir al río Magdalena.", category:"Oficios que Permanecen" },
  { img:"images/port-cocuy-eterno.jpg", title:"El Cocuy eterno", story:"Los glaciares de Güicán resisten, cada año un poco más pequeños.", category:"Entre Agua y Montaña" },
  { img:"images/port-guican-01.jpg", title:"Sendero de altura", story:"Caminar el páramo es leer un país que pocos alcanzan a ver de cerca.", category:"Entre Agua y Montaña" },
  { img:"images/port-rio-guayabero.jpg", title:"El río Guayabero", story:"Entre selva y sabana, el Guayabero serpentea por el corazón de la Macarena.", category:"Entre Agua y Montaña" },
  { img:"images/port-desierto-rojo.jpg", title:"El desierto rojo", story:"Entre cactus y cañones de arcilla, la Tatacoa parece un paisaje de otro planeta.", category:"Colombia Inesperada" },
  { img:"images/port-esculturas-arena.jpg", title:"Esculturas de arena", story:"El viento y el agua tallaron durante siglos estas formaciones únicas del país.", category:"Colombia Inesperada" },
  { img:"images/port-mar-siete-colores.jpg", title:"El mar de los siete colores", story:"En Providencia, el Caribe alcanza tonos de turquesa que parecen imposibles.", category:"Entre Agua y Montaña" },
  { img:"images/port-formaciones-desierto.jpeg", title:"El tablero bajo el árbol", story:"En un patio de La Guajira, un tablero improvisado le recuerda a los niños por qué vale la pena aprender a leer.", category:"Guardianes del Tiempo" },
  { img:"images/port-amanecer-guajiro.jpg", title:"Amanecer guajiro", story:"Muelle en Riohacha, el primer sol del día se asoma sobre el mar Caribe.", category:"Instantes de Silencio" },
  { img:"images/port-amanecer-sabanero.jpg", title:"Amanecer sabanero", story:"La niebla se levanta lentamente sobre los potreros de la sabana.", category:"Instantes de Silencio" },
  { img:"images/port-palmeras-atardecer.jpg", title:"Silencio de palmeras", story:"El sol se esconde detrás de una hilera de palmas que se duplican en el agua.", category:"Instantes de Silencio" },
  { img:"images/port-valle-verde.jpg", title:"Valle bajo la nieve", story:"Un valle glaciar guarda pequeñas lagunas entre pajonales dorados.", category:"Entre Agua y Montaña" },
  { img:"images/port-rio-atardecer.jpg", title:"Río al atardecer", story:"El cielo se incendia sobre las aguas tranquilas de un río de tierra caliente.", category:"Instantes de Silencio" },
  { img:"images/port-arena-arboles.jpg", title:"Dibujos de marea", story:"El agua que retrocede deja sobre la arena formas que parecen árboles.", category:"Instantes de Silencio" },

  { img:"images/port-alas-escarlata.jpg", title:"Alas escarlata", story:"Colombia guarda uno de los mayores tesoros de biodiversidad aviar del planeta.", category:"Geografías Vivas" },
  { img:"images/port-cielo-escarlata.jpg", title:"Cielo escarlata", story:"Miles de corocoras tiñen de rojo el cielo de los Llanos orientales.", category:"Geografías Vivas" },
  { img:"images/port-salto-mar.jpg", title:"Un salto en el mar", story:"Frente a la costa, un delfín rompe la calma del océano Pacífico.", category:"Colombia Inesperada" },
  { img:"images/port-centinela-humedal.jpg", title:"El centinela del humedal", story:"Este ave vigila su territorio desde lo alto de la vegetación.", category:"Geografías Vivas" },
  { img:"images/port-mirada-caracara.jpg", title:"Mirada de caracara", story:"En los llanos, este cazador terrestre recorre el suelo en busca de su presa.", category:"Geografías Vivas" },
  { img:"images/port-festin-papaya.jpg", title:"Festín de papaya", story:"Un carpintero se alimenta entre las frutas maduras de un papayo silvestre.", category:"Colombia Inesperada" },
  { img:"images/port-cocli-vigilante.jpg", title:"El cocli vigilante", story:"Con su pico curvo, recorre los humedales en busca de alimento.", category:"Geografías Vivas" },
  { img:"images/port-equilibrista-agua.jpg", title:"El equilibrista del agua", story:"Sus largos dedos le permiten caminar sobre las plantas flotantes del humedal.", category:"Geografías Vivas" },
  { img:"images/port-vuelo-rasante.jpg", title:"Vuelo rasante", story:"En pleno vuelo, esta garza atraviesa el verde infinito de la sabana.", category:"Instantes de Silencio" },
  { img:"images/port-rosa-humedal.jpg", title:"Rosa en el humedal", story:"Sus alas rosadas tiñen por un instante el cielo gris del pantano.", category:"Instantes de Silencio" },
  { img:"images/port-baile-colibries.jpg", title:"El baile de los colibríes", story:"Docenas de colibríes se disputan el néctar en un solo instante suspendido.", category:"Colombia Inesperada" },
  { img:"images/port-plumaje-fuego.jpg", title:"Plumaje de fuego", story:"El colorido de esta guacamaya resume la paleta entera del trópico colombiano.", category:"Geografías Vivas" },
  { img:"images/port-bandada-palma.jpg", title:"Bandada en la palma", story:"Una bandada completa se disputa el mismo árbol al caer la tarde.", category:"Geografías Vivas" },
  { img:"images/port-cazador-rio.jpg", title:"El cazador del río", story:"Inmóvil sobre un cable, el martín pescador espera su próximo movimiento.", category:"Instantes de Silencio" },
  { img:"images/port-ojos-amarillos.jpg", title:"Ojos amarillos", story:"El búho terrero observa el mundo desde la boca de su propia madriguera.", category:"Colombia Inesperada" },
  { img:"images/port-dulce-encuentro.jpg", title:"Dulce encuentro", story:"El turpial, ave nacional, encuentra en la fruta madura su recompensa diaria.", category:"Colombia Inesperada" },
];
